### PR TITLE
Add a factory for 6.9.14

### PR DESCRIPTION
**Pull request by missedone**
for #40 

ping @juherr

### CODE REVIEW

**Comment by juherr** [comment]
LGTM 👍

**Comment by juherr** [comment]
@missedone Could you just rebase the branch?

**Comment by missedone** [comment]
I'm not sure what do you mean, can you do it at your side?

**Comment by missedone** [comment]
@juherr . rebased. please follow up to merge this (probably with LGTM? 😄 )

**Comment by juherr** [comment]
LGTM

**Comment by juherr** [comment]
You can merge it but "This branch is out of sync with the base branch.
Changes from the base branch must be synced with this branch before merging" 
Strange.

**Comment by juherr** [comment]
In fact I can't merge: Server error. Please try again.

**Pull request merged**
